steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "functions",
        "deploy",
        "hellohttp",
        "--region=us-central1",
        "--runtime=python39",
        "--trigger-http",
        "--entry-point=hello_http",
        "--source=.",
        "--allow-unauthenticated",
      ]
    timeout: "1200s"

options:
  logging: CLOUD_LOGGING_ONLY
